name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Download Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O sdk-tools.zip
        unzip sdk-tools.zip -d $HOME/android-sdk
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "$HOME/android-sdk/cmdline-tools/bin" >> $GITHUB_PATH
        mkdir -p $HOME/.android && echo '### User Sources for Android SDK Manager' > $HOME/.android/repositories.cfg
        yes | sdkmanager --licenses
        sdkmanager "platforms;android-34" "build-tools;34.0.0"

    - name: Grant execute permission for gradlew
      run: chmod +x ./android/gradlew

    - name: Build with Gradle
      run: ./android/gradlew assembleRelease

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: app-release
        path: android/app/build/outputs/apk/release/*.apk