name: Capacitor Android Build

on:
  push:
    branches:
      - main  # Replace with your desired triggering branch(es)
  pull_request:
    branches:
      - main  # Replace with your desired triggering branch(es)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17 (Recommended)
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'  # Adjust based on your project requirements

    - name: Install Capacitor CLI and dependencies
      run: |
        npm install @capacitor/cli @capacitor/core
        npm install

    - name: Build Web Assets (Optional)
      # Replace with your project's specific build command if needed
      run: npm run build  # e.g., npm run build

    - name: Sync Capacitor with Android project
      uses: Narottam04/action-capacitor-android@v1.0.0  # Consider using latest version
      with:
        # Check the action's documentation for available inputs and their usage
        # - capacitorPath: path/to/your/capacitor.config.json  # (Optional)
        # - androidManifestPath: path/to/your/android/app/src/main/AndroidManifest.xml  # (Optional)
        # - gradlePath: path/to/your/android/gradle.properties  # (Optional)
        # - gradleWrapperPath: path/to/your/gradle/wrapper/gradle-wrapper.properties  # (Optional)
        # - androidBuildVariant: debug|release  # Defaults to 'release'
        # - cleanBuild: true|false  # Defaults to 'false'

    - name: Install Android SDK (Consider caching)
      # Replace with your preferred installation method or use a caching action
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip

    - name: Build Android App with Capacitor
      uses: Narottam04/action-capacitor-android@v1.0.0  # Consider using latest version
      with:
        androidBuildVariant: debug|release  # Specify your desired build variant
        # Refer to documentation for other relevant inputs

    - name: Upload APK (Optional)
      uses: actions/upload-artifact@v3
      with:
        name: app-${{ github.sha }}.apk
        path: android/app/build/outputs/apk/${{ job.steps.filter({ name: 'Build Android App with Capacitor' }).outputs[0] }}